### PR TITLE
Adds "noindex" meta tag to header

### PR DESCRIPTION
**Pull request by stopfstedt**
see https://developers.google.com/search/docs/advanced/crawling/block-indexing

### CODE REVIEW

**Comment by Trott** [comment]
Does this omit the tag on the home page? Our `robots.txt` permits indexing of the home page. (Aside: I'm not seeing the `robots.txt` in the theme repo or in the UCSF Moodle repo so I'm not sure where it comes from.)

**Comment by stopfstedt** [comment]
> Does this omit the tag on the home page?
as discussed yesterday, it currently doesn't. i'm taking this back to the workbench.

> Aside: I'm not seeing the `robots.txt` in the theme repo or in the UCSF Moodle repo so I'm not sure where it comes from.
Filed as separate issue: https://github.com/ucsf-ckm/moodle-theme-ucsf/issues/131

**Comment by stopfstedt** [comment]
For reference, Moodle has config settings that will add the `noindex` meta tag to the header as configured.
However, it doesn't have a "exclude everything but the frontpage" option. 

image

and it's also doesn't generate a corresponding `robots.txt` file either.

so our approach to do some custom coding here is legit.

**Comment by ctam** [comment]
Is there any way we can just add a new option here in the dropdown box?

**Comment by stopfstedt** [comment]
> Is there any way we can just add a new option here in the dropdown box?

not without cracking moodle core open. in other words, unfortunately not.

**Comment by stopfstedt** [comment]
@ctam - this is ready for review now.

**Pull request merged**
