### PR TITLE
reworked readme file.

### PR DESCRIPTION
**Pull request by stopfstedt**
- added screenshot
- removed gunk
- added copyright notice
- linked to CLE website

### CODE REVIEW

**Comment by Trott** [comment]
Is the "gunk" stuff that belongs in a `CHANGELOG` file, maybe? I'm fine with getting rid of it entirely if you and Carson are comfortable with that. Just asking.

**Comment by ctam** [comment]
Yes, I would recommend moving the "gunk" stuff to a `CHANGELOG` file.  These files are imported from Lambda Solutions, and one of these days if we need further development from them, we could ask them to merge our changes with theirs before they start building on top.  @stopfstedt, can you purge the "gunk" stuff into a separate `CHANGELOG` file, please?

**Comment by stopfstedt** [comment]
agreed on adding a changelog file.
however, the contents in the current readme is IMO garbage and should be thrown out. we currently have no tagged releases. 
i propose we start afresh with the first "official" release of this project. this ties in with #6.

**Comment by stopfstedt** [comment]
@ctam i added a changelog file, referencing this [release](https://github.com/ucsf-ckm/moodle-theme-ucsf/releases/tag/1.0.0) as version 1.0.0.
that release still contains the old, garbagy README file.

**Comment by ctam** [comment]
Hmm...if you disagree to keep the content of the current README file as history/change log, there's no point in creating a  CHANGELOG file, which results to one more file we have to keep up-to-date.  Let's toss that and add the following line into `version.php` along with your `1.0.0` tag.  

`$plugin->release = 'v1.0.0';`

(ref. https://docs.moodle.org/dev/version.php)

**Comment by stopfstedt** [comment]
good point regarding the release info in the version file, this has been added.

the change log file _will_ provide more useful info going forward, starting with the next release.

**Pull request merged**
